[package]
name = "dead-ringer"
version = "1.2.0"
edition = "2021"
description = "Dring, A Binary Diff Utility"
authors = ["Zackary Troop"]

[[bin]]
name = "dring"
path = "src/main.rs"

[dependencies]
ratatui = { version = "0.30.0", features = ["crossterm"] }
crossterm = "0.29"
base64 = "0.22.1"
